insert into mall_item 
(mit_id,
mit_key,
mit_name,
mit_order,
mit_type1,
mit_type2,
mit_type3,
mit_status,
mit_summary,
mit_content,
mit_mobile_content,
mit_price,
`mit_file_1 ~ mit_file_10`) 
values 
(1,
null,
'레귤러 캣브리쉬 데님',
null,
1,
1,
1,
1,
'- 부담없는 일자핏으로 데일리로 활용 가능 - 무겁지 않은 소재로 사계절 착장 가능 - 늘어짐 걱정 없이 입을 수 있는 탄탄한 원단',
'핏감 / 일자핏 두께감 / 얇음 신축성 / 없음 비침 / 없음 안감 / 없음',
'핏감 / 일자핏 두께감 / 얇음 신축성 / 없음 비침 / 없음 안감 / 없음',
17000,
'B레귤러캣브리쉬.jpg');